### ISSUE TITLE
File types filter not working in Firefox

### ISSUE THREAD

**Issue by ajmath** [JonRowe/phoenix_live_view_dropzone#1]
Hello and thanks for making this library.  I have integrated this into our app and everything is working as expected except for the file types filter in Firefox.  I've verified the filter works as expected with Safari and Chrome.  I'm running macOS Catalina for my OS.  Here is the relevant integration snippet:
```elixir
live_component @socket, PhoenixLiveViewDropzone,
  file_data: @file_data,
  dom_id: input_id,
  button_text: " ",
  css_class: "image-upload-touch-target",
  file_types: ["image/jpeg", "image/gif", "image/png", "image/svg+xml", "image/webp"]
```

**Comment by JonRowe** [comment]
Thanks for the heads up, I will have a look to see if this can be fixed, the file type filtering is more of a nicety for the browser UI anyway, (the browser does not guarantee an image uploaded is an image after all) so it does need to be checked server side as well after upload.

**Comment by JonRowe** [comment]
:wave: I'm archiving this project as I feel LiveViews own file upload solutions will be better supported.
