### ISSUE TITLE
Multiple files in drag and drop

### ISSUE THREAD

**Issue by speeddragon** [JonRowe/phoenix_live_view_dropzone#11]
Hi, first thanks for this module. I've tried to drag and drop multiple files at once, but it only sends the first one. Do you know if it is possible to support multiple files?

**Comment by mattdb** [comment]
It is _possible_-- a multiple file drop does work for me in my implementation. Dropzone invokes the "generate-url" event once _per_ file. Not sure what's going wrong for you, are you able to set up an SSCCE or steps to reproduce?

**Comment by JonRowe** [comment]
Yep it was designed with multiple file uploads in mind, but to my knowledge my use case (uploading to S3) only supports one file at a time so its one file one event, but you should be able to drag and drop multiple to trigger an event cycle for each file.

**Comment by speeddragon** [comment]
Thanks for the reply. @mattdb I just simply drag multiple files into the button, but only one event is created. I will check again and create an example to reproduce this behaviour.

**Comment by JonRowe** [comment]
Sorry for the delay, finally had time to get back to file uploads in my app, I've tested in chrome and OS X on my app and it creates two events and uploads two files, both from selecting with the dialogue, and dropping multiple files, so a reproduction would help find any issues!

**Comment by speeddragon** [comment]
Just tested right now, and it works. Maybe I had some error in the code killing the second upload. Thanks!
