### ISSUE TITLE
Please add ability to resize images before uploading

### ISSUE THREAD

**Issue by ajaynamika** [JonRowe/phoenix_live_view_dropzone#14]
Hi,

Thank you for the good work you have done. It's helping many people.
I think a fairly common use case would be to resize images before uploading.

Any chance it can be added? This would really really help.

Good job once again.

**Comment by JonRowe** [comment]
:wave: Nothing so far in this is image specific, and I don't use it for uploading images, so this isn't something I am interested in adding, I would look at a PR if someone else wanted to add this optionally for images.

**Comment by JonRowe** [comment]
:wave: I'm archiving this project as I feel LiveViews own file upload solutions would be better supported, so this feature request is closed sorry.
