### ISSUE TITLE
Installation instructions version issue. 

### ISSUE THREAD

**Issue by Ivor** [JonRowe/phoenix_live_view_dropzone#2]
Hi. Thanks, this looks super useful. 
The readme suggests version 0.1.0 but when installing the latest version is 0.0.6 which is also the latest tag I can see in the source here.

**Comment by JonRowe** [comment]
Sorry I had hoped to release `0.1.0` as a sort of "final first version", I've fixed the readme for now, wish there was a way for that to reflect the actual version automatically I'm sure I'll forget to bump it again :joy:

Thanks for reporting.
