### ISSUE TITLE
Can you create a simple example

### ISSUE THREAD

**Issue by gregoribic** [JonRowe/phoenix_live_view_dropzone#3]
When posting/uploading I get an error, probably related to csrf_token.

Request: PUT /uploads
** (exit) an exception was raised:
    ** (ArgumentError) cannot fetch key "_csrf_token" from conn.body_params because they were not fetched
        (plug 1.10.0) lib/plug/conn/unfetched.ex:35: Plug.Conn.Unfetched.raise_unfetched/3

**Comment by JonRowe** [comment]
I'm going to close this as its out of scope, the component doesn't implement an upload controller leaving that to you. This worked for me locally, after adding `:plug` to extra applications:

```
defmodule UploadController do
  use MyApp.Web, :controller

  def create(conn, params) do
    IO.inspect read_body(conn)
    conn |> send_resp(200, "OK")
  end
end
```

**Comment by gregoribic** [comment]
Hi,

I tried to solve the issue. I found out that when posting / you use PUT
action, socket's private struct is empty.
So also _csrf_token is missing for proper form processing.


Lep pozdrav / Best Regards,
Gregor Ibic
_________________________

INTELICOM d.o.o.
E: gregor.ibic@intelicom.si
W: www.intelicom.si
T: +386 40 754 233
_________________________
intelicom logo
 cid:image004.png@01D496FB.2254AF80  cid:image005.png@01D496FB.2254AF80
cid:image007.png@01D496FB.2254AF80

**Comment by JonRowe** [comment]
Hi Gregor

You need to provide the csrf token yourself via the url, its designed for signed urls, its not a phoenix form action.

There is no socket used, its just uploaded to the url you give as the body of the request, this is pretty standard for uploads to 3rd party file systems and its possible to simulate with the controller I commented on the issue with (I tested it worked).

Cheers
Jon Rowe
---------------------------
mail@jonrowe.co.uk
jonrowe.co.uk

**Comment by nehemieOT** [comment]
Hi,

I'm encountering also the same issue. I tried everything mentioned above ( I do have a controller endpoints, the url I set to `file_data` during the "generate-url" event is well linked to it. I'm also having `:plug` in my extra_applications, I do provide the "_csrf_token" param on my url request as mentioned in your last answer, with a token generated from `Phoenix.Controller` module (I do assign it from my mount function) ). But still I'm unable to by pass this error. 

 Is there something I'm missing ?

Thanks in advance.

Nehemie

**Comment by JonRowe** [comment]
@nehemieOT Apologies but I have no idea, the simple example above works with a freshly generated phoenix app with the `:plug` extra_application, I don't have the time to debug other peoples applications as I do uploads straight to S3, sorry!

**Comment by nehemieOT** [comment]
@JonRowe Alright, thanks for the quick answer, no problem ;) !

**Comment by nehemieOT** [comment]
@gregoribic is there any chances you fixed it  ?

**Comment by gregoribic** [comment]
I tried for some time, but then I coded a liveview view and component to display uploads. This view/component combination refresh automatically. And on the other part an ajax upload button with some animation when uploading. Works fine and simple to add to any form/template.

**Comment by nehemieOT** [comment]
@gregoribic So yo just gave up with this component and tried the other work around that can be found on the pheonix_liveview issue related to upload, right ?

**Comment by nehemieOT** [comment]
@JonRowe Hello so, finally I went for a straight upload to s3 as well, but I'm pretty lost on how to generate the presigned_url. Any exemple on how to set up a valide path for an object I didnt uploaded yet?

like : `ExAws.Config.new(:s3) |> ExAws.S3.presigned_url(:put, "my-bucket", filepath)` to be generated in the "generate-url" event I guess. But how to get a valide file path ? At this point I only have an id and a filename.

An exemple would be very much appreciated, Thanks !

**Comment by JonRowe** [comment]
You can use any path you like, heres my code for that:

```
defmodule MyApp.Data.Files do
  @moduledoc """
  Handles uploading / downloading files.
  """

  alias MyApp.Data.{File, Repo}

  def generate_upload_url(path) do
    {:ok, _url} = ExAws.S3.presigned_url(config(), :put, bucket(), path, query_params: [], virtual_host: true)
  end

  defp bucket do
    Application.get_env(:data, :s3_upload_bucket)
  end

  defp config do
    ExAws.Config.new(:s3)
    |> Map.put(:region, region())
  end

  defp region do
    Application.get_env(:data, :s3_upload_region)
  end
end

```

I typically use the uploaded filename plus the users id and a prefix. so I'd call `MyApp.Data.Files.generate_upload_path("tmp/#{id}/#{filename}")`

**Comment by nehemieOT** [comment]
Many thanks !
