### ISSUE TITLE
File metadata before upload begins

### ISSUE THREAD

**Issue by mazz** [JonRowe/phoenix_live_view_dropzone#31]
Is there a way to get simple file metadata before the upload begins(or even during upload)? Something like file size in bytes? Ideally I'd like access to the file pointer so that I can use `ffprobe` on it for media metadata but not knowing the internals of the component(and very alien to elm) I don't know if that would be logistically possible. The reason I would like this information is I want to be able to help the user pre-fill a form during or after it has uploaded.

**Comment by JonRowe** [comment]
:wave: I'm archiving this project as I feel LiveViews own file upload solutions would be better supported, certainly with there uploaders you could access the meta data before upload.
