### ISSUE TITLE
Class attributes for inner div and button element?

### ISSUE THREAD

**Issue by tukruic** [JonRowe/phoenix_live_view_dropzone#5]
Is there any way to set this from live_component declaration? im using tailwind css and it would be much easier to apply styles, Thanks! also, great work ^^

**Comment by JonRowe** [comment]
:wave: The outer div is customisable for a class, and the inner div just fills it, does that not meet your needs?

I can add an option to customise the button class, I'm just a fan of using less but more semantic css classes and using selectors so things like tailwind tend to pass me by! :joy:

**Comment by JonRowe** [comment]
I can release the button class tweak later today if that suffices?

**Comment by JonRowe** [comment]
I've released `0.0.8` which allows customising the button.
