### ISSUE TITLE
Updating target does not change callback

### ISSUE THREAD

**Issue by mattdb** [JonRowe/phoenix_live_view_dropzone#7]
First, thanks for this super useful live component!

I've stumbled upon a bug in my special corner case:

When using target _and_ the Dropzone component is re-rendered with a new target, the JavaScript glue code isn't changing the ports subscriptions, resulting in liveView trying to push an event to a target that doesn't exist (or at a minimum is the wrong one!).

Picture a list of comments, and any _one_ of them can be edited at a time, and the edit form includes the dropzone. Dropzone works great for the first form rendered on a page, but when the comment being edited is switched, then we have the disconnect. (LiveView preserves the component if it is just moving to another location on the page with new data). It can be worked around by rendering an intermediate page with no dropzone in it, but that's obviously a bit clunky.

I'd be happy to submit a PR, though I'm feeling a bit unsure how to produce a failing test case on this one. I don't think the `updated()` callback is currently being tested? The JS update seems pretty small, just maintaining and checking the target value very similarly to the `dataId` & `dataUrl` tracking currently being done.

**Comment by JonRowe** [comment]
Closed in #9
